"""
Stage 1 crawler for the FeatureBased Skill Generator Agent.

Walks a Java repository, parses .java / .xml / .properties / .yml / .sql / .sh
files locally, and emits a single JSON index. Zero AI calls. Deterministic.

This is the foundation Stage 2 (Plan) and Stage 3 (Generate) feed off. Per the
pipeline spec (AGENT.md and artifact 2), this stage spends no tokens — it's
pure local file parsing.

Public API:
    crawl(repo_root, *, extra_excludes=set(), include_tests=True) -> CrawlIndex

CLI entry point lives in skill_generator.cli; this module can also be run
directly:
    python -m skill_generator.crawler <repo-root>
"""
from __future__ import annotations

import json
import re
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

# ─────────────────────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────────────────────

TOOL_VERSION = "0.2.0"
SCHEMA_VERSION = 2

DEFAULT_EXCLUDE_DIRS = {
    "target", "build", ".git", "generated", ".mvn",
    "node_modules", ".idea", ".vscode", ".gradle",
    "out", "dist", ".settings",
    # Note: "bin/" intentionally NOT excluded — legacy apps put shell scripts there.
    # Eclipse compiled output (.class files) inside bin/ is still filtered by BINARY_EXTENSIONS.
}

BINARY_EXTENSIONS = {
    ".class", ".jar", ".war", ".ear", ".zip", ".tar", ".gz",
    ".so", ".dylib", ".dll", ".png", ".jpg", ".jpeg", ".gif", ".pdf",
    ".ico", ".keystore", ".jks", ".woff", ".woff2", ".ttf",
}

MIN_FILE_CHARS = 10
GOD_CLASS_LINES = 300
MAX_ANNOTATIONS = 5
MAX_METHOD_NAMES = 10
MAX_IMPORT_TAIL_TOKENS = 6

GENERATED_MARKERS = ("// DO NOT EDIT", "@Generated", "// generated by")

CONFIG_PREFIXES_OF_INTEREST = (
    "datasource", "spring.datasource", "mail", "spring.mail",
    "file", "batch", "spring.batch", "queue", "scheduler",
    "quartz", "kafka", "redis", "app", "logging",
)

# ─────────────────────────────────────────────────────────────────────────────
# Regex parsers (lightweight — no full Java AST library)
# ─────────────────────────────────────────────────────────────────────────────

RE_PACKAGE = re.compile(r"^\s*package\s+([\w.]+)\s*;", re.MULTILINE)
RE_IMPORT = re.compile(r"^\s*import\s+(?:static\s+)?([\w.]+(?:\.\*)?)\s*;", re.MULTILINE)
RE_TYPE_DECL = re.compile(
    r"^\s*(?:public|private|protected)?\s*"
    r"(?:(?:abstract|final|static|sealed|non-sealed)\s+)*"
    r"(class|interface|enum|record)\s+"
    r"(\w+)"
    r"(?:\s*<[^>]+>)?"
    r"(?:\s+extends\s+([\w.<>,\s]+?))?"
    r"(?:\s+implements\s+([\w.<>,\s?]+?))?"
    r"\s*[\{(]",
    re.MULTILINE,
)
RE_ANNOTATION = re.compile(r"^\s*@(\w+)", re.MULTILINE)
RE_METHOD = re.compile(
    r"^\s*(?:public|private|protected)\s+"
    r"(?:(?:static|final|abstract|synchronized|default|native)\s+)*"
    r"(?:<[^>]+>\s+)?"
    r"[\w<>,\[\]?.\s]+?\s+"
    r"(\w+)\s*\("
    r"[^)]*\)"
    r"(?:\s*throws\s+[\w.,\s]+)?"
    r"\s*[\{;]",
    re.MULTILINE,
)
RE_DEPRECATED_ANN = re.compile(r"@Deprecated\b")
RE_DEPRECATED_DOC = re.compile(r"\*\s*@deprecated", re.IGNORECASE)
RE_TEST_FILENAME = re.compile(r"(Test|Tests|IT)\.java$")

# Strip line/block comments so they don't pollute method/annotation extraction.
RE_BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)
RE_LINE_COMMENT = re.compile(r"//[^\n]*")
RE_STRING_LITERAL = re.compile(r'"(?:[^"\\]|\\.)*"')


# ─────────────────────────────────────────────────────────────────────────────
# Data model
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class JavaClass:
    file_path: str
    package: str | None
    class_name: str
    type: str  # class | interface | enum | record
    annotations: list = field(default_factory=list)
    method_names: list = field(default_factory=list)
    extends: str | None = None
    implements: list = field(default_factory=list)
    import_tail_tokens: list = field(default_factory=list)
    line_count: int = 0
    flags: list = field(default_factory=list)


@dataclass
class XmlSignal:
    file_path: str
    xml_type: str   # web_xml | struts_config | spring_context | hibernate_cfg | hbm | persistence | quartz | unknown
    signals: list = field(default_factory=list)


@dataclass
class ConfigSignal:
    file_path: str
    config_type: str   # properties | yaml
    key_prefixes: list = field(default_factory=list)


@dataclass
class SqlSignal:
    file_path: str
    sql_kind: str       # migration | stored_proc | ddl | mixed
    procedures: list = field(default_factory=list)   # CREATE PROCEDURE / FUNCTION names
    tables: list = field(default_factory=list)       # CREATE TABLE names
    views: list = field(default_factory=list)        # CREATE VIEW names
    altered_tables: list = field(default_factory=list)
    flags: list = field(default_factory=list)        # flyway_migration | liquibase | callable_from_java


@dataclass
class ShellSignal:
    file_path: str
    java_invocations: list = field(default_factory=list)   # FQNs of Java classes invoked
    java_jars: list = field(default_factory=list)          # JAR names invoked
    sql_invocations: list = field(default_factory=list)    # psql / mysql / sqlplus + .sql refs
    env_vars: list = field(default_factory=list)           # SPRING_PROFILES_ACTIVE, JAVA_OPTS, etc.


@dataclass
class CrawlIndex:
    schema_version: int
    scan: dict
    stats: dict
    warnings: list
    java_classes: list           # list[JavaClass]
    xml_signals: list            # list[XmlSignal]
    config_signals: list         # list[ConfigSignal]
    sql_signals: list = field(default_factory=list)     # list[SqlSignal]
    shell_signals: list = field(default_factory=list)   # list[ShellSignal]


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _strip_java_noise(src: str) -> str:
    """Remove block comments, line comments, and string literals from Java source
    before regex parsing. This avoids matching @annotations or method-like
    constructs inside comments or strings."""
    src = RE_BLOCK_COMMENT.sub("", src)
    src = RE_LINE_COMMENT.sub("", src)
    src = RE_STRING_LITERAL.sub('""', src)
    return src


def _split_csv_types(s: str | None) -> list:
    if not s:
        return []
    # Drop generic parameters so "Comparable<Foo>" → "Comparable"
    out = []
    depth = 0
    buf = []
    for ch in s:
        if ch == "<":
            depth += 1
            continue
        if ch == ">":
            depth -= 1
            continue
        if depth > 0:
            # Inside a generic parameter list — strip it entirely so
            # "JpaRepository<FileDeliveryEntity, Long>" → "JpaRepository"
            continue
        if ch == "," and depth == 0:
            piece = "".join(buf).strip()
            if piece:
                out.append(piece)
            buf = []
        else:
            buf.append(ch)
    piece = "".join(buf).strip()
    if piece:
        out.append(piece)
    return out


def _import_tail_tokens(imports: list) -> list:
    """For each import, take its last two dot-segments; dedupe; cap at the limit.
    Example: 'org.springframework.web.bind.annotation.RestController' → 'annotation.RestController'."""
    seen = []
    for imp in imports:
        parts = imp.split(".")
        if len(parts) >= 2:
            tail = ".".join(parts[-2:])
        else:
            tail = imp
        if tail not in seen:
            seen.append(tail)
        if len(seen) >= MAX_IMPORT_TAIL_TOKENS:
            break
    return seen


def _file_is_too_small(path: Path) -> bool:
    try:
        return path.stat().st_size < MIN_FILE_CHARS
    except OSError:
        return True


def _is_generated(raw_src: str) -> bool:
    head = raw_src[:2048]
    return any(m in head for m in GENERATED_MARKERS)


# ─────────────────────────────────────────────────────────────────────────────
# Java parsing
# ─────────────────────────────────────────────────────────────────────────────

def parse_java_file(path: Path, repo_root: Path) -> tuple:
    """
    Parse a single .java file. Returns (java_classes_list, warning_or_none).
    A file with multiple top-level types yields one JavaClass entry per type
    (rare but valid).
    """
    try:
        raw = path.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        return [], f"unreadable: {path} ({e})"

    if len(raw) < MIN_FILE_CHARS:
        return [], None

    file_is_generated = _is_generated(raw)
    if file_is_generated:
        return [], None  # silently skip per spec

    src = _strip_java_noise(raw)
    line_count = raw.count("\n") + 1

    package_match = RE_PACKAGE.search(src)
    package = package_match.group(1) if package_match else None

    imports = [m.group(1) for m in RE_IMPORT.finditer(src)]
    tail = _import_tail_tokens(imports)

    # Annotations file-wide (we only care about first MAX_ANNOTATIONS at top of file)
    annotations = []
    for m in RE_ANNOTATION.finditer(src):
        name = m.group(1)
        if name not in annotations:
            annotations.append(name)
        if len(annotations) >= MAX_ANNOTATIONS:
            break

    method_names = []
    for m in RE_METHOD.finditer(src):
        name = m.group(1)
        # Skip pseudo-method matches that look like control flow
        if name in {"if", "for", "while", "switch", "catch", "return", "synchronized"}:
            continue
        if name not in method_names:
            method_names.append(name)
        if len(method_names) >= MAX_METHOD_NAMES:
            break

    rel_path = path.relative_to(repo_root).as_posix()
    fname = path.name

    # Flags
    base_flags = []
    if RE_DEPRECATED_ANN.search(src) or RE_DEPRECATED_DOC.search(raw):
        base_flags.append("deprecated")
    if line_count > GOD_CLASS_LINES:
        base_flags.append("god_class")
    if RE_TEST_FILENAME.search(fname) or "/test/" in rel_path or "/tests/" in rel_path:
        base_flags.append("test")

    type_matches = list(RE_TYPE_DECL.finditer(src))
    if not type_matches:
        # Probably package-info.java or similar — emit a stub entry so downstream
        # tools know the file existed.
        return [
            JavaClass(
                file_path=rel_path,
                package=package,
                class_name=path.stem,
                type="unknown",
                annotations=annotations,
                method_names=[],
                extends=None,
                implements=[],
                import_tail_tokens=tail,
                line_count=line_count,
                flags=base_flags,
            )
        ], None

    results = []
    for tm in type_matches:
        type_kind = tm.group(1)
        class_name = tm.group(2)
        extends_raw = tm.group(3)
        implements_raw = tm.group(4)
        extends_list = _split_csv_types(extends_raw)
        implements_list = _split_csv_types(implements_raw)
        # For interfaces and records, "extends" can be a comma-separated list.
        # We expose extends as the first one for class/enum, and join all for interface.
        if type_kind == "interface":
            extends_val = ", ".join(extends_list) if extends_list else None
        else:
            extends_val = extends_list[0] if extends_list else None

        results.append(
            JavaClass(
                file_path=rel_path,
                package=package,
                class_name=class_name,
                type=type_kind,
                annotations=annotations,
                method_names=method_names,
                extends=extends_val,
                implements=implements_list,
                import_tail_tokens=tail,
                line_count=line_count,
                flags=list(base_flags),
            )
        )
    return results, None


# ─────────────────────────────────────────────────────────────────────────────
# XML parsing
# ─────────────────────────────────────────────────────────────────────────────

def _strip_xml_ns(tag: str) -> str:
    return tag.split("}", 1)[-1] if "}" in tag else tag


def _classify_xml(root: ET.Element, fname: str) -> str:
    tag = _strip_xml_ns(root.tag)
    fname_lower = fname.lower()
    ns = root.tag.split("}", 1)[0].lstrip("{") if "}" in root.tag else ""
    if tag == "web-app" or fname_lower == "web.xml":
        return "web_xml"
    if tag == "struts-config" or "struts" in fname_lower:
        return "struts_config"
    # Spring Batch — looks like <beans> but with a batch namespace, OR a <job> element.
    if "springframework.org/schema/batch" in ns:
        return "spring_batch"
    if tag == "beans":
        # Look for a Spring Batch <job> child to disambiguate.
        for child in root.iter():
            if _strip_xml_ns(child.tag) == "job":
                return "spring_batch"
        return "spring_context"
    if tag == "hibernate-configuration":
        return "hibernate_cfg"
    if tag == "hibernate-mapping" or fname_lower.endswith(".hbm.xml"):
        return "hbm"
    if tag == "persistence" or fname_lower == "persistence.xml":
        return "persistence"
    if "quartz" in fname_lower or tag in {"job-scheduling-data", "quartz"}:
        return "quartz"
    return "unknown"


def parse_xml_file(path: Path, repo_root: Path) -> tuple:
    try:
        raw = path.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        return None, f"unreadable: {path} ({e})"
    if len(raw) < MIN_FILE_CHARS:
        return None, None
    try:
        root = ET.fromstring(raw)
    except ET.ParseError as e:
        return None, f"xml-parse-error: {path} ({e})"

    rel = path.relative_to(repo_root).as_posix()
    xml_type = _classify_xml(root, path.name)
    signals = []

    def iter_all(elem):
        yield elem
        for child in elem:
            yield from iter_all(child)

    if xml_type == "web_xml":
        url_patterns_by_name = {}
        servlet_classes_by_name = {}
        for el in iter_all(root):
            tag = _strip_xml_ns(el.tag)
            if tag == "servlet":
                name = None
                cls = None
                for sub in el:
                    stag = _strip_xml_ns(sub.tag)
                    if stag == "servlet-name":
                        name = (sub.text or "").strip()
                    elif stag == "servlet-class":
                        cls = (sub.text or "").strip()
                if name and cls:
                    servlet_classes_by_name[name] = cls
            elif tag == "servlet-mapping":
                name = None
                url = None
                for sub in el:
                    stag = _strip_xml_ns(sub.tag)
                    if stag == "servlet-name":
                        name = (sub.text or "").strip()
                    elif stag == "url-pattern":
                        url = (sub.text or "").strip()
                if name and url:
                    url_patterns_by_name.setdefault(name, []).append(url)
        for name, cls in servlet_classes_by_name.items():
            for url in url_patterns_by_name.get(name, []):
                signals.append({"kind": "servlet_mapping", "name": name, "url_pattern": url, "class": cls})

    elif xml_type == "struts_config":
        for el in iter_all(root):
            if _strip_xml_ns(el.tag) == "action":
                path_attr = el.attrib.get("path")
                type_attr = el.attrib.get("type")
                if path_attr and type_attr:
                    signals.append({"kind": "struts_action", "path": path_attr, "class": type_attr})

    elif xml_type == "spring_context":
        for el in iter_all(root):
            if _strip_xml_ns(el.tag) == "bean":
                bean_id = el.attrib.get("id") or el.attrib.get("name")
                bean_class = el.attrib.get("class")
                if bean_id and bean_class:
                    signals.append({"kind": "bean", "id": bean_id, "class": bean_class})

    elif xml_type == "hibernate_cfg":
        for el in iter_all(root):
            if _strip_xml_ns(el.tag) == "mapping":
                cls = el.attrib.get("class")
                res = el.attrib.get("resource")
                signals.append({"kind": "hibernate_mapping_ref", "class": cls, "resource": res})

    elif xml_type == "hbm":
        for el in iter_all(root):
            tag = _strip_xml_ns(el.tag)
            if tag in {"class", "subclass", "joined-subclass"}:
                cls = el.attrib.get("name")
                table = el.attrib.get("table")
                if cls:
                    signals.append({"kind": "hibernate_mapping", "class": cls, "table": table})

    elif xml_type == "persistence":
        for el in iter_all(root):
            if _strip_xml_ns(el.tag) == "class":
                cls = (el.text or "").strip()
                if cls:
                    signals.append({"kind": "jpa_entity", "class": cls})

    elif xml_type == "spring_batch":
        for el in iter_all(root):
            tag = _strip_xml_ns(el.tag)
            if tag == "job":
                job_id = el.attrib.get("id")
                if job_id:
                    signals.append({"kind": "batch_job", "id": job_id})
            elif tag == "step":
                step_id = el.attrib.get("id")
                if step_id:
                    signals.append({"kind": "batch_step", "id": step_id})
            elif tag in {"tasklet", "chunk"}:
                ref = el.attrib.get("ref") or el.attrib.get("reader") or el.attrib.get("writer")
                if ref:
                    signals.append({"kind": "batch_component", "tag": tag, "ref": ref})

    elif xml_type == "quartz":
        # Multiple variants: Quartz 1.x job-scheduling-data, Quartz 2.x with <schedule>
        current_job = None
        for el in iter_all(root):
            tag = _strip_xml_ns(el.tag)
            if tag == "job" or tag == "job-detail":
                current_job = {"kind": "quartz_job", "class": None, "name": None, "cron": None}
                for sub in el:
                    stag = _strip_xml_ns(sub.tag)
                    if stag in {"job-class"}:
                        current_job["class"] = (sub.text or "").strip()
                    elif stag in {"name"}:
                        current_job["name"] = (sub.text or "").strip()
                if current_job["class"]:
                    signals.append(dict(current_job))
            elif tag in {"cron", "cron-expression"}:
                cron_val = (el.text or "").strip()
                if signals and signals[-1].get("kind") == "quartz_job":
                    signals[-1]["cron"] = cron_val

    # Skip XML with no useful signals
    if not signals and xml_type == "unknown":
        return None, None
    return XmlSignal(file_path=rel, xml_type=xml_type, signals=signals), None


# ─────────────────────────────────────────────────────────────────────────────
# Properties / YAML parsing
# ─────────────────────────────────────────────────────────────────────────────

def _extract_properties_prefixes(text: str) -> list:
    """Return distinct prefix keys (everything before the first dot or =) that
    match CONFIG_PREFIXES_OF_INTEREST or look meaningful."""
    seen = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("!"):
            continue
        # key=value or key:value
        for sep in ("=", ":"):
            if sep in line:
                key = line.split(sep, 1)[0].strip()
                break
        else:
            continue
        if not key:
            continue
        top = key.split(".", 1)[0]
        prefix_full = ".".join(key.split(".")[:2]) if "." in key else key
        if prefix_full not in seen:
            seen.append(prefix_full)
    return seen


def _extract_yaml_prefixes(text: str) -> list:
    """Return top-level YAML keys plus second-level keys for the most interesting
    prefixes. Implementation is intentionally simple (line-based) — we only need
    prefixes, not values."""
    seen = []
    stack = []   # [(indent, key)]
    for line in text.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        # Pure-YAML lines we care about look like 'key:' or 'key: value'
        indent = len(line) - len(line.lstrip(" "))
        stripped = line.strip()
        if ":" not in stripped:
            continue
        key = stripped.split(":", 1)[0].strip()
        if not key or not re.match(r"^[A-Za-z_][\w.-]*$", key):
            continue
        # Pop deeper or equal indents
        while stack and stack[-1][0] >= indent:
            stack.pop()
        stack.append((indent, key))
        path = ".".join(k for _, k in stack)
        # Keep top-level and second-level prefixes
        if path.count(".") <= 1 and path not in seen:
            seen.append(path)
    return seen


def parse_config_file(path: Path, repo_root: Path) -> tuple:
    try:
        raw = path.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        return None, f"unreadable: {path} ({e})"
    if len(raw) < MIN_FILE_CHARS:
        return None, None
    rel = path.relative_to(repo_root).as_posix()
    suffix = path.suffix.lower()
    if suffix == ".properties":
        prefixes = _extract_properties_prefixes(raw)
        ctype = "properties"
    elif suffix in {".yml", ".yaml"}:
        prefixes = _extract_yaml_prefixes(raw)
        ctype = "yaml"
    else:
        return None, None
    if not prefixes:
        return None, None
    return ConfigSignal(file_path=rel, config_type=ctype, key_prefixes=prefixes), None


# ─────────────────────────────────────────────────────────────────────────────
# SQL parsing — stored procs, DDL, migrations
# ─────────────────────────────────────────────────────────────────────────────

RE_SQL_CREATE_PROC = re.compile(
    r"\bCREATE\s+(?:OR\s+REPLACE\s+)?(?:PROCEDURE|FUNCTION)\s+(?:IF\s+NOT\s+EXISTS\s+)?([\w.`\"]+)",
    re.IGNORECASE,
)
RE_SQL_CREATE_TABLE = re.compile(
    r"\bCREATE\s+(?:TEMPORARY\s+)?TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([\w.`\"]+)",
    re.IGNORECASE,
)
RE_SQL_CREATE_VIEW = re.compile(
    r"\bCREATE\s+(?:OR\s+REPLACE\s+)?VIEW\s+([\w.`\"]+)",
    re.IGNORECASE,
)
RE_SQL_ALTER_TABLE = re.compile(
    r"\bALTER\s+TABLE\s+(?:IF\s+EXISTS\s+)?([\w.`\"]+)",
    re.IGNORECASE,
)
RE_FLYWAY_NAMING = re.compile(r"^V[\d_]+__\w+\.sql$|^R__\w+\.sql$", re.IGNORECASE)
RE_LIQUIBASE_NAMING = re.compile(r"changelog|changeset", re.IGNORECASE)


def _clean_sql_name(raw: str) -> str:
    return raw.strip("`\"[]").strip()


def parse_sql_file(path: Path, repo_root: Path) -> tuple:
    try:
        raw = path.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        return None, f"unreadable: {path} ({e})"
    if len(raw) < MIN_FILE_CHARS:
        return None, None

    rel = path.relative_to(repo_root).as_posix()
    fname = path.name

    procedures = []
    for m in RE_SQL_CREATE_PROC.finditer(raw):
        name = _clean_sql_name(m.group(1))
        if name and name not in procedures:
            procedures.append(name)
    tables = []
    for m in RE_SQL_CREATE_TABLE.finditer(raw):
        name = _clean_sql_name(m.group(1))
        if name and name not in tables:
            tables.append(name)
    views = []
    for m in RE_SQL_CREATE_VIEW.finditer(raw):
        name = _clean_sql_name(m.group(1))
        if name and name not in views:
            views.append(name)
    altered = []
    for m in RE_SQL_ALTER_TABLE.finditer(raw):
        name = _clean_sql_name(m.group(1))
        if name and name not in altered:
            altered.append(name)

    if not (procedures or tables or views or altered):
        return None, None

    # Classify kind
    if procedures and not tables:
        kind = "stored_proc"
    elif tables and not procedures:
        kind = "ddl"
    elif procedures and tables:
        kind = "mixed"
    elif altered:
        kind = "ddl"
    else:
        kind = "ddl"

    flags = []
    # Flyway / Liquibase naming
    if RE_FLYWAY_NAMING.match(fname):
        flags.append("flyway_migration")
        kind = "migration"
    if "liquibase" in rel.lower() or "changelog" in rel.lower():
        flags.append("liquibase")
        kind = "migration"
    if procedures:
        flags.append("callable_from_java")

    return SqlSignal(
        file_path=rel,
        sql_kind=kind,
        procedures=procedures,
        tables=tables,
        views=views,
        altered_tables=altered,
        flags=flags,
    ), None


# ─────────────────────────────────────────────────────────────────────────────
# Shell-script parsing — invocations, env, SQL hooks
# ─────────────────────────────────────────────────────────────────────────────

RE_SH_JAVA_CLASS = re.compile(r"\bjava\b[^\n]*?\s([\w.]+\.[A-Z]\w+)")
RE_SH_JAR = re.compile(r"\b-jar\s+([\w./-]+\.jar)\b")
RE_SH_PSQL = re.compile(r"\b(?:psql|mysql|sqlplus|sqlcmd|mongo|cqlsh)\b[^\n]*?(?:-f\s+|<\s*)([\w./-]+\.sql)")
RE_SH_ENV_VAR = re.compile(r"\b(SPRING_PROFILES_ACTIVE|JAVA_OPTS|JAVA_HOME|CLASSPATH|MAVEN_OPTS|GRADLE_OPTS|DB_URL|DATABASE_URL)\b")


def parse_shell_file(path: Path, repo_root: Path) -> tuple:
    try:
        raw = path.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        return None, f"unreadable: {path} ({e})"
    if len(raw) < MIN_FILE_CHARS:
        return None, None

    rel = path.relative_to(repo_root).as_posix()

    java_classes_invoked = []
    for m in RE_SH_JAVA_CLASS.finditer(raw):
        cls = m.group(1)
        if cls not in java_classes_invoked:
            java_classes_invoked.append(cls)

    jars = []
    for m in RE_SH_JAR.finditer(raw):
        j = m.group(1)
        if j not in jars:
            jars.append(j)

    sql_invocations = []
    for m in RE_SH_PSQL.finditer(raw):
        sql_invocations.append(m.group(1))

    env_vars = []
    for m in RE_SH_ENV_VAR.finditer(raw):
        v = m.group(1)
        if v not in env_vars:
            env_vars.append(v)

    if not (java_classes_invoked or jars or sql_invocations or env_vars):
        return None, None

    return ShellSignal(
        file_path=rel,
        java_invocations=java_classes_invoked,
        java_jars=jars,
        sql_invocations=sql_invocations,
        env_vars=env_vars,
    ), None


# ─────────────────────────────────────────────────────────────────────────────
# Walker
# ─────────────────────────────────────────────────────────────────────────────

def _iter_files(repo_root: Path, extra_excludes: set) -> Iterable:
    excludes = DEFAULT_EXCLUDE_DIRS | set(extra_excludes)
    for path in repo_root.rglob("*"):
        # Skip excluded directories anywhere in the tree
        parts = set(path.parts)
        if parts & excludes:
            continue
        if not path.is_file():
            continue
        if path.suffix.lower() in BINARY_EXTENSIONS:
            continue
        yield path


def _detect_framework(java_classes: list, xml_signals: list) -> str:
    """Best-effort framework label based on what we found."""
    anns = set()
    for jc in java_classes:
        anns.update(jc.annotations)
    has_spring_boot = "SpringBootApplication" in anns
    has_rest_controller = "RestController" in anns or "Controller" in anns
    has_path = "Path" in anns  # JAX-RS / Quarkus
    has_struts = any(s.xml_type == "struts_config" for s in xml_signals)
    has_spring_xml = any(s.xml_type == "spring_context" for s in xml_signals)
    has_hibernate_cfg = any(s.xml_type in {"hibernate_cfg", "hbm"} for s in xml_signals)
    has_web_xml = any(s.xml_type == "web_xml" for s in xml_signals)

    if has_spring_boot:
        return "Spring Boot"
    if has_path and not has_rest_controller:
        return "Quarkus"
    if has_struts:
        return "Struts"
    if has_rest_controller and (has_spring_xml or not has_web_xml):
        return "Spring MVC"
    if has_hibernate_cfg and has_web_xml:
        return "Spring MVC (legacy)"
    if has_web_xml and not has_rest_controller:
        return "Raw Servlet"
    return "Unknown"


def _detect_build_system(repo_root: Path) -> str:
    if (repo_root / "pom.xml").exists():
        return "Maven"
    if (repo_root / "build.gradle").exists() or (repo_root / "build.gradle.kts").exists():
        return "Gradle"
    if (repo_root / "build.xml").exists():
        return "Ant"
    return "Unknown"


def _normalize_java_version(raw: str) -> str:
    """Map '1.8' to '8', strip JavaVersion.VERSION_17 prefix, etc."""
    raw = raw.strip().lstrip("v").lstrip("V")
    if raw.startswith("VERSION_"):
        raw = raw[len("VERSION_"):]
    if "." in raw:
        major, minor = raw.split(".", 1)
        if major == "1":
            return minor
        return major
    return raw


def _detect_java_version(repo_root: Path) -> str:
    pom = repo_root / "pom.xml"
    if pom.exists():
        try:
            raw = pom.read_text(encoding="utf-8", errors="replace")
        except OSError:
            raw = ""
        m = re.search(
            r"<(?:maven\.compiler\.)?(?:source|target|release)>\s*([\d.]+)\s*</",
            raw,
        )
        if m:
            return _normalize_java_version(m.group(1))
    # Gradle (build.gradle or build.gradle.kts)
    for gradle_file in ("build.gradle", "build.gradle.kts"):
        gf = repo_root / gradle_file
        if gf.exists():
            try:
                raw = gf.read_text(encoding="utf-8", errors="replace")
                m = re.search(
                    r"(?:sourceCompatibility|targetCompatibility|jvmTarget)\s*=?\s*['\"]?"
                    r"(?:JavaVersion\.)?([\w.]+)",
                    raw,
                )
                if m:
                    return _normalize_java_version(m.group(1))
            except OSError:
                pass
    return "Unknown"


# ─────────────────────────────────────────────────────────────────────────────
# Public entry point
# ─────────────────────────────────────────────────────────────────────────────

def crawl(repo_root: str | Path, *, extra_excludes: set | None = None,
          include_tests: bool = True) -> CrawlIndex:
    """Walk the repo and return a CrawlIndex. Pure local — no AI calls."""
    repo_root = Path(repo_root).resolve()
    if not repo_root.is_dir():
        raise ValueError(f"Not a directory: {repo_root}")

    extra_excludes = set(extra_excludes or [])
    warnings: list = []
    java_classes: list = []
    xml_signals: list = []
    config_signals: list = []
    sql_signals: list = []
    shell_signals: list = []
    skipped = 0

    for path in _iter_files(repo_root, extra_excludes):
        suffix = path.suffix.lower()
        try:
            if suffix == ".java":
                results, warn = parse_java_file(path, repo_root)
                if warn:
                    warnings.append(warn)
                for jc in results:
                    if "test" in jc.flags and not include_tests:
                        skipped += 1
                        continue
                    java_classes.append(jc)
            elif suffix == ".xml":
                result, warn = parse_xml_file(path, repo_root)
                if warn:
                    warnings.append(warn)
                if result is not None:
                    xml_signals.append(result)
            elif suffix in {".properties", ".yml", ".yaml"}:
                result, warn = parse_config_file(path, repo_root)
                if warn:
                    warnings.append(warn)
                if result is not None:
                    config_signals.append(result)
            elif suffix in {".sql", ".ddl"}:
                result, warn = parse_sql_file(path, repo_root)
                if warn:
                    warnings.append(warn)
                if result is not None:
                    sql_signals.append(result)
            elif suffix in {".sh", ".bash"}:
                result, warn = parse_shell_file(path, repo_root)
                if warn:
                    warnings.append(warn)
                if result is not None:
                    shell_signals.append(result)
            else:
                skipped += 1
        except Exception as e:  # pragma: no cover — defensive
            warnings.append(f"unexpected-error: {path} ({type(e).__name__}: {e})")
            skipped += 1

    total_loc = sum(jc.line_count for jc in java_classes)
    framework = _detect_framework(java_classes, xml_signals)
    build_system = _detect_build_system(repo_root)
    java_version = _detect_java_version(repo_root)

    project_type = _infer_project_type(java_classes, xml_signals, sql_signals, shell_signals, framework)

    if not java_classes and not xml_signals and not sql_signals:
        warnings.append("zero-source-files: no Java/XML/SQL found under repo root")

    return CrawlIndex(
        schema_version=SCHEMA_VERSION,
        scan={
            "root": str(repo_root),
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "tool_version": TOOL_VERSION,
        },
        stats={
            "java_classes": len(java_classes),
            "xml_files": len(xml_signals),
            "config_files": len(config_signals),
            "sql_files": len(sql_signals),
            "shell_files": len(shell_signals),
            "skipped_files": skipped,
            "total_java_loc": total_loc,
            "framework": framework,
            "build_system": build_system,
            "java_version": java_version,
            "project_type": project_type,
        },
        warnings=warnings,
        java_classes=java_classes,
        xml_signals=xml_signals,
        config_signals=config_signals,
        sql_signals=sql_signals,
        shell_signals=shell_signals,
    )


def _infer_project_type(java_classes: list, xml_signals: list,
                        sql_signals: list, shell_signals: list, framework: str) -> str:
    has_rest = any("RestController" in jc.annotations or "Controller" in jc.annotations
                   or "Path" in jc.annotations for jc in java_classes)
    has_batch = any("EnableBatchProcessing" in jc.annotations or "Job" in jc.annotations
                    for jc in java_classes) or any(
        s.xml_type == "spring_batch" for s in xml_signals
    )
    has_scheduled = any("Scheduled" in jc.annotations for jc in java_classes) or any(
        s.xml_type == "quartz" for s in xml_signals
    )
    has_stored_procs = any(s.sql_kind in {"stored_proc", "mixed"} for s in sql_signals)
    has_shell_orchestration = any(s.java_invocations or s.java_jars for s in shell_signals)

    if has_rest and (has_batch or has_scheduled):
        return "Hybrid"
    if has_rest:
        return "REST API"
    if has_batch:
        return "Batch Job"
    if has_scheduled:
        return "Scheduled"
    if has_stored_procs and has_shell_orchestration:
        return "Legacy (stored-proc + shell)"
    if has_stored_procs:
        return "Stored-Procedure Driven"
    if framework == "Raw Servlet" or any(s.xml_type == "web_xml" for s in xml_signals):
        return "Monolith Module"
    return "Unknown"


# ─────────────────────────────────────────────────────────────────────────────
# CLI-style invocation
# ─────────────────────────────────────────────────────────────────────────────

def _to_json(index: CrawlIndex) -> str:
    return json.dumps(asdict(index), indent=2, ensure_ascii=False, default=str)


def _main(argv: list) -> int:
    if len(argv) < 2:
        print("Usage: python -m skill_generator.crawler <repo-root> [--output FILE]", file=sys.stderr)
        return 2
    repo_root = argv[1]
    output = None
    if "--output" in argv:
        i = argv.index("--output")
        output = argv[i + 1] if i + 1 < len(argv) else None
    index = crawl(repo_root)
    out = _to_json(index)
    if output:
        Path(output).write_text(out)
    else:
        print(out)
    return 0


if __name__ == "__main__":
    sys.exit(_main(sys.argv))
